{{- define "ingressProxy.deploymentSpec"}}
{{- if .Values.ingress.enabled }}
{{- $image := .Values.ingressProxy.deployment.image }}
{{- if .Values.global  }}
{{- $image = merge .Values.ingressProxy.deployment.image .Values.global.image }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "gloo.labels" . | indent 4}}
    gloo: {{ .Values.ingressProxy.label }}
  name: ingress-proxy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.ingressProxy.deployment.replicas }}
  selector:
    matchLabels:
      gloo: ingress-proxy
  template:
    metadata:
      labels:
        gloo: {{ .Values.ingressProxy.label }}
        {{- if .Values.ingressProxy.deployment.extraIngressProxyLabels }}
        {{- range $key, $value := .Values.ingressProxy.deployment.extraIngressProxyLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.global.istioIntegration.disableAutoinjection }}
        sidecar.istio.io/inject: "false"
        {{- end }}
      annotations:
        checksum/ingress-envoy-config: {{ include (print .Template.BasePath "/12-ingress-proxy-configmap.yaml") . | sha256sum }}
        {{- if .Values.ingressProxy.deployment.extraAnnotations }}
        {{- range $key, $value := .Values.ingressProxy.deployment.extraAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      {{- include "gloo.pullSecret" $image | nindent 6 -}}
      containers:
      - args: ["--disable-hot-restart"]
        env:
{{- if .Values.ingressProxy.deployment.customEnv }}
{{ toYaml .Values.ingressProxy.deployment.customEnv | indent 8 }}
{{- end }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INGRESS_PROXY_LABEL
          value: {{ .Values.ingressProxy.label }}
        image: {{template "gloo.image" $image}}
        imagePullPolicy: {{ $image.pullPolicy }}
        name: ingress-proxy
{{- if .Values.ingressProxy.deployment.resources }}
        resources:
{{ toYaml .Values.ingressProxy.deployment.resources | indent 10}}
{{- end}}
        {{- $capabilities := dict "drop" (list "ALL") "add" (list "NET_BIND_SERVICE") -}}
        {{- $securityDefaults := dict
            "readOnlyRootFilesystem" true
            "allowPrivilegeEscalation" false
            "capabilities" $capabilities
        }}
        {{- if .Values.ingressProxy.deployment.runAsUser  -}}
          {{- $_ := set $securityDefaults "runAsUser" .Values.ingressProxy.deployment.runAsUser }}
        {{- end -}}
        {{- include "gloo.containerSecurityContext" (dict "values" .Values.ingressProxy.deployment.ingressProxyContainerSecurityContext "defaults" $securityDefaults "podSecurityStandards" .Values.global.podSecurityStandards "indent" 8 "globalSec" .Values.global.securitySettings) }}
        ports:
        - containerPort: {{ .Values.ingressProxy.deployment.httpPort }}
          name: http
          protocol: TCP
        - containerPort: {{ .Values.ingressProxy.deployment.httpsPort }}
          name: https
          protocol: TCP
{{- with .Values.ingressProxy.deployment.extraPorts }}
{{toYaml  . | indent 8}}{{- end }}
        volumeMounts:
        - mountPath: /etc/envoy
          name: envoy-config
      volumes:
      - configMap:
          name: ingress-envoy-config
        name: envoy-config
      {{- include "gloo.podSpecStandardFields" .Values.ingress.deployment | nindent 6 -}}
{{- end }} {{/* if .Values.ingress.enabled */}}
{{- end }} {{/* define "ingressProxy.deploymentSpec "*/}}

{{/* Render template with yaml overrides */}}
{{- $kubeResourceOverride := dict -}}
{{- if .Values.ingressProxy -}}
{{- if .Values.ingressProxy.deployment -}}
{{- $kubeResourceOverride = .Values.ingressProxy.deployment.kubeResourceOverride  -}}
{{- end -}}
{{- end -}}
{{- include "gloo.util.merge" (list . $kubeResourceOverride "ingressProxy.deploymentSpec") -}}
