{{ define "gloo.serviceSpec" }}
{{- $statsConfig := coalesce .Values.gloo.deployment.stats .Values.global.glooStats -}}
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "gloo.labels" . | indent 4}}
    gloo: gloo
  name: gloo
  namespace: {{ .Release.Namespace }}
spec:
{{- if .Values.gloo.deployment.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.gloo.deployment.externalTrafficPolicy }}
{{- end }}
  ports:
  - name: grpc-xds
    port: {{ .Values.gloo.deployment.xdsPort }}
    protocol: TCP
  - name: rest-xds
    port: {{ .Values.gloo.deployment.restXdsPort }}
    protocol: TCP
  - name: grpc-validation
    port: {{ .Values.gloo.deployment.validationPort }}
    protocol: TCP
  - name: grpc-proxydebug
    port: {{ .Values.gloo.deployment.proxyDebugPort }}
    protocol: TCP
  - name: wasm-cache
    port: 9979
    protocol: TCP
{{- if and .Values.gateway.enabled .Values.gateway.validation.enabled }}
  - name: https
    port: 443
    protocol: TCP
    # this should map to projects/gateway/pkg/defaults.ValidationWebhookBindPort
    targetPort: 8443
{{- end }}
{{- if and $statsConfig.enabled $statsConfig.serviceMonitorEnabled }}
  - name: http-monitoring
    port: 9091
{{- end }}
{{- if .Values.settings.devMode }}
  - name: dev-admin
    port: 10010
    protocol: TCP
{{- end }}
  selector:
    gloo: gloo
{{- end }} {{/* define "gloo.serviceSpec "*/}}

{{/* Render template with yaml overrides */}}
{{- $kubeResourceOverride := dict -}}
{{- if .Values.gloo.service -}}
{{- if .Values.gloo.service.kubeResourceOverride -}}
{{- $kubeResourceOverride = .Values.gloo.service.kubeResourceOverride  -}}
{{- end -}}
{{- end -}}

{{- include "gloo.util.merge" (list . $kubeResourceOverride "gloo.serviceSpec") -}}
