{{- define "knativeExternalProxy.deploymentSpec"}}
{{- if .Values.settings.integrations.knative.enabled }}
{{- if (semverCompare ">= 0.8.0" .Values.settings.integrations.knative.version ) }}
{{- $image := .Values.settings.integrations.knative.proxy.image }}
{{- if .Values.global  }}
{{- $image = merge .Values.settings.integrations.knative.proxy.image .Values.global.image  }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "gloo.labels" . | indent 4}}
    gloo: knative-external-proxy
  name: knative-external-proxy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.settings.integrations.knative.proxy.replicas }}
  selector:
    matchLabels:
      gloo: knative-external-proxy
  template:
    metadata:
      labels:
        gloo: knative-external-proxy
        {{- if .Values.settings.integrations.knative.extraKnativeExternalLabels }}
        {{- range $key, $value := .Values.settings.integrations.knative.extraKnativeExternalLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.global.istioIntegration.disableAutoinjection }}
        sidecar.istio.io/inject: "false"
        {{- end }}
      annotations:
        checksum/knative-external-proxy-config: {{ include (print .Template.BasePath "/27-knative-external-proxy-configmap.yaml") . | sha256sum }}
        {{- if .Values.settings.integrations.knative.extraKnativeExternalAnnotations }}
        {{- range $key, $value := .Values.settings.integrations.knative.extraKnativeExternalAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      {{- include "gloo.pullSecret" $image | nindent 6 -}}
      {{- include "gloo.podSpecStandardFields" .Values.settings.integrations.knative.proxy | nindent 6 -}}
      containers:
      - args: ["--disable-hot-restart"]
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: {{ template "gloo.image" $image }}
        imagePullPolicy: {{ $image.pullPolicy }}
        name: knative-external-proxy
{{- if .Values.settings.integrations.knative.proxy.resources }}
        resources:
{{ toYaml .Values.settings.integrations.knative.proxy.resources | indent 10}}
{{- end}}
        {{- $capabilities := dict "drop" (list "ALL") "add" (list "NET_BIND_SERVICE") -}}
        {{- $securityDefaults := dict 
            "readOnlyRootFilesystem" true
            "allowPrivilegeEscalation" false
            "capabilities" $capabilities
        }}
       {{- if .Values.settings.integrations.knative.proxy.runAsUser -}}
          {{- $_ := set $securityDefaults "runAsUser" .Values.settings.integrations.knative.proxy.runAsUser }}
        {{- end -}}
        {{- include "gloo.containerSecurityContext" (dict "values" .Values.settings.integrations.knative.proxy.containerSecurityContext "defaults" $securityDefaults "podSecurityStandards" .Values.global.podSecurityStandards "indent" 8 "globalSec" .Values.global.securitySettings) }}
        ports:
        - containerPort: {{ .Values.settings.integrations.knative.proxy.httpPort }}
          name: http
          protocol: TCP
        - containerPort: {{ .Values.settings.integrations.knative.proxy.httpsPort }}
          name: https
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/envoy
          name: envoy-config
      volumes:
      - configMap:
          name: knative-external-proxy-config
        name: envoy-config

{{- end }}
{{- end }}
{{- end }} {{/* define knativeExternalProxy.deploymentSpec */}}

{{/* Render template with yaml overrides */}}
{{- $kubeResourceOverride := dict -}}
{{- if .Values.settings.integrations.knative.proxy -}}
{{- if .Values.settings.integrations.knative.proxy.deployment -}}
{{- $kubeResourceOverride = .Values.settings.integrations.knative.proxy.deployment.kubeResourceOverride  -}}
{{- end -}}
{{- end -}}
{{- include "gloo.util.merge" (list . $kubeResourceOverride "knativeExternalProxy.deploymentSpec") -}}