{{- range $configMap := .Values.global.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ required "A ConfigMap name is required!" $configMap.name }}
  namespace: {{ $configMap.namespace | default $.Release.Namespace }}
  labels:
{{ include "gloo.labels" $ | indent 4}}
    gloo: gloo
data:
  {{- range $key, $value := $configMap.data}}
  {{ $key }}: {{ $value }}
  {{- end }}
---
{{- end }}
