{{- if .Values.kubeGateway.enabled -}}
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  labels:
    {{- include "gloo-gateway.constLabels" . | nindent 4 }}
  name: gloo-gateway
spec:
  controllerName: solo.io/gloo-gateway
  parametersRef:
    group: gateway.gloo.solo.io
    kind: GatewayParameters
    name: gloo-gateway
    namespace: {{ .Release.Namespace }}
{{- end }}{{/* if .Values.kubeGateway.enabled */}}
