{{- if .Values.kubeGateway.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gloo-gateway.fullname" . }}.{{.Release.Namespace}}
  labels:
    {{- include "gloo-gateway.constLabels" . | nindent 4 }}
    {{- include "gloo-gateway.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "gateway.networking.k8s.io"
  resources:
  - gatewayclasses
  - gateways
  - httproutes
  - referencegrants
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - endpoints
  - secrets
  - namespaces
  verbs: ["get", "list", "watch"]
- apiGroups:
  - "discovery.k8s.io"
  resources:
  - endpointslices
  verbs: ["get", "list", "watch"]
- apiGroups:
  - "gateway.solo.io"
  resources:
  - routeoptions
  - virtualhostoptions
  - listeneroptions
  - httplisteneroptions
  verbs: ["get", "list", "watch"]
- apiGroups:
  - "gateway.networking.k8s.io"
  resources:
  - gatewayclasses/status
  - gateways/status
  - httproutes/status
  verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "gloo-gateway.constLabels" . | nindent 4 }}
    {{- include "gloo-gateway.labels" . | nindent 4 }}
  name: {{ include "gloo-gateway.fullname" . }}.{{.Release.Namespace}}-binding
subjects:
- kind: ServiceAccount
  name: gloo
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "gloo-gateway.fullname" . }}.{{.Release.Namespace}}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gloo-gateway.fullname" . }}-deploy.{{.Release.Namespace}}
  labels:
    {{- include "gloo-gateway.constLabels" . | nindent 4 }}
    {{- include "gloo-gateway.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "gateway.gloo.solo.io"
  resources:
  - gatewayparameters
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - services
  - serviceaccounts
  - configmaps
  verbs: ["get", "list", "watch", "patch", "create"]
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs: ["get", "list", "watch", "patch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "gloo-gateway.constLabels" . | nindent 4 }}
    {{- include "gloo-gateway.labels" . | nindent 4 }}
  name: {{ include "gloo-gateway.fullname" . }}-deploy.{{.Release.Namespace}}-binding
subjects:
- kind: ServiceAccount
  name: gloo
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "gloo-gateway.fullname" . }}-deploy.{{.Release.Namespace}}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
