{{- if .Values.gateway.cleanupJob.enabled }}
{{- if .Values.global.glooRbac.create }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-resource-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "gloo.labels" . | indent 4}}
    gloo: rbac
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0" # must be created before cleanup job
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
- apiGroups: ["gloo.solo.io"]
  resources: ["*"]
  verbs: ["list", "delete"]
{{- end }}{{/* if .Values.global.glooRbac.create */}}
{{- end }}{{/* if .Values.gateway.cleanupJob.enabled  */}}
