{{- if .Values.gateway.rolloutJob.enabled }}
{{- if .Values.global.glooRbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "gloo.labels" . | indent 4}}
    gloo: rbac
  name: gloo-resource-rollout
  namespace: {{ .Release.Namespace }}
{{- end -}}{{/* if .Values.global.glooRbac.create */}}
{{- end }}{{/* if .Values.gateway.rolloutJob.enabled  */}}
