{{- if .Values.enabled }}
{{ if .Values.create_license_secret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "gloofed.labels" . | indent 4}}
    gloo-fed: license
  name: {{ .Values.license_secret_name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  license-key: {{ required "A license key is required!" .Values.license_key | b64enc | quote }}
{{- end }}
{{- end }} {{/* .Values.enabled */}}
