license_key: foobar-not-valid-does-this-work

ambient:
  waypoint:
    enabled: true

gloo:
  kubeGateway:
    enabled: true

  gloo:
    deployment:
      customEnv:
        # The waypoint translator is disabled by default, so must explicitly enable it
        - name: ENABLE_WAYPOINTS
          value: "true"
      image:
        pullPolicy: Always
        repository: gloo-ee
        # the PR tag has latest/what's merging, but may contain a bug that duplicates RBAC filters (up to 255x!)
        # tag: PR-6666
        tag: slandow/gloo-ee:authz-perf
        # actually respect the tag
        digest: ""
        distrolessDigest: ""
        fipsDigest: ""
        fipsDistrolessDigest: ""

global:
  extensions:
    extAuth:
      enabled: false
    rateLimit:
      enabled: false

observability:
  enabled: false

prometheus:
  enabled: false
