{{- if $.Values.gloo.kubeGateway.enabled -}}
{{- if $.Values.ambient.waypoint.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "gloo.roleKind" . }}
metadata:
  name: gloo-waypoint-control-plane{{ include "gloo.rbacNameSuffix" . }}
  {{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app: gloo
rules: # These rules match the Portal resource rules used in GME for portal server, mesh management, and the mesh agent.
- apiGroups: ["security.istio.io"]
  verbs: [ "get", "watch", "list" ]
  resources:
  - "authorizationpolicies"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "gloo.roleKind" . }}Binding
metadata:
  name: gloo-waypoint-control-plane-binding{{ include "gloo.rbacNameSuffix" . }}
  {{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app: gloo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ include "gloo.roleKind" . }}
  name: gloo-waypoint-control-plane{{ include "gloo.rbacNameSuffix" . }}
subjects:
- kind: ServiceAccount
  name: gloo
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- end }}
