{{- if .Values.global.extensions.rateLimit.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "gloo.labels" . | indent 4}}
    gloo: {{ .Values.global.extensions.rateLimit.service.name }}
  name: {{ .Values.global.extensions.rateLimit.service.name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
