{{- if .Values.global.extensions.extAuth.enabled }}
{{- $extAuth := .Values.global.extensions.extAuth }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "gloo.labels" . | indent 4}}
    gloo: {{ $extAuth.service.name }}
  name: {{ $extAuth.service.name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
