{{- if .Values.global.extensions.caching.enabled }}
{{- $caching := .Values.global.extensions.caching }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "gloo.labels" . | indent 4}}
    gloo: {{ $caching.name }}
  name: {{ $caching.name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
