{{- $statsConfig := coalesce .Values.observability.deployment.stats .Values.global.glooStats }}
{{- if $statsConfig.serviceMonitorEnabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "gloo.labels" . | indent 4}}
    gloo: observability
  name: observability
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http-monitoring
      port: 9091
  selector:
    gloo: observability
{{- end }} {{/* if $statsConfig.serviceMonitorEnabled */}}